### PR TITLE
Layout and Release Tool fixes

### PR DESCRIPTION
**Pull request by justarandomgeek**
Moving the files to the top level of the repo allows it to be cloned into the Factorio mods tree directly while developing. It also allows the use of `git archive` to automatically build a package with names consistent with info.json, as the included release script does.

### CODE REVIEW

**Comment by DedlySpyder** [comment]
Thanks for the script and idea of moving everything around, but I've never used git from the command line, and after trying for a few hours I've run into some issues with it and am tired of trying for today. I may come back to this later and see if I can figure it out.

**Comment by justarandomgeek** [comment]
You should be able to use this with whatever git tools you were already using (I mostly use TortoiseGit, command line git is for scripting), the different interfaces to git all work together. Let me know if you want some help figuring this out. (Or, check out some of my other recent repos for other examples of this layout/script).

The basic idea is: you use whatever git tool you like to clone the repo directly into $Factorio\mods\modname_1.1.1\, and you can work on your mod there, where you can also test it in-place. Then, when you're ready to release a new version, you update info.json and the directory name, commit that, and run the script and out pops a pre-built zip file ready for the mod portal or other distribution methods, and a git tag to mark when that version was built in the git log. The tag also shows as a Release on github when pushed, giving you a place to post zips here if you want.

**Comment by justarandomgeek** [comment]
I rebased this to work on top of your 0.3.5 update more cleanly.

**Comment by DedlySpyder** [comment]
So, I tried out the script, but it doesn't make a good zip for me to use. The zip is called _.zip and a few layers in has the mod files, but with Git appended to the from of the names to everything.

I'm not sure what is up with that. I'm using Windows 7 if that helps at all.

**Comment by justarandomgeek** [comment]
You probably don't have [jq](https://stedolan.github.io/jq/), which I used jq to read the version information out of info.json. Download the Windows build, rename it from jq-win64.exe to just jq.exe and put it somewhere that's included in your PATH.

**Comment by DedlySpyder** [comment]
Ok cool I got it to work (though it doesn't make a tag because of my other Git issues), I'll have to add something like this to my other mods. Thanks a bunch!

**Pull request merged**
